# Generated by Django 5.1.6 on 2025-03-01 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_chapterbookings_delete_chapteravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='chapters.chapter')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.DeleteModel(
            name='ChapterBookings',
        ),
    ]
