# Generated by Django 5.1.6 on 2025-03-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_chapter_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
