# Generated by Django 5.1.6 on 2025-03-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_chapter_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='cost',
            new_name='cost_per_month',
        ),
    ]
