# Generated by Django 5.1.6 on 2025-03-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_rename_cost_chapter_cost_per_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='cost_per_month',
        ),
        migrations.AddField(
            model_name='chapter',
            name='cost_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per night in USD', max_digits=10),
        ),
    ]
