# Generated by Django 5.1.6 on 2025-03-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0008_remove_chapter_cost_per_month_chapter_cost_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this chapter', null=True, upload_to='chapter_images/'),
        ),
    ]
