# Generated by Django 5.1.6 on 2025-03-10 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0009_chapter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='image',
        ),
        migrations.CreateModel(
            name='ChapterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image for this chapter', upload_to='chapter_images/')),
                ('order', models.IntegerField(default=0, help_text='Order in which the image will be displayed')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chapters.chapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
