# Generated by Django 5.1.6 on 2025-03-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0010_remove_chapter_image_chapterimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='image',
            field=models.ImageField(upload_to='chapter_images/'),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
