# Generated by Django 5.1.6 on 2025-03-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0011_alter_chapter_description_alter_chapterimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='image',
            field=models.ImageField(help_text='Upload an image for this chapter', upload_to='chapter_images/'),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which the image will be displayed'),
        ),
    ]
