# Generated by Django 5.1.6 on 2025-03-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0012_alter_chapter_description_alter_chapterimage_image_and_more'),
        ('colivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coliver',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colivers', to='chapters.chapter'),
        ),
    ]
