# Generated by Django 5.1.6 on 2025-02-27 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noncoliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Enter a valid phone number.')], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('why_join', models.TextField(verbose_name='Why do you want to join?')),
                ('resume', models.FileField(blank=True, upload_to='resumes/', verbose_name='Optional upload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted On')),
            ],
            options={
                'verbose_name': 'Non-Coliver',
                'verbose_name_plural': 'Non-Colivers',
            },
        ),
    ]
