# Generated by Django 5.1.6 on 2025-03-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('why_join', models.TextField(verbose_name='Why did you join?')),
                ('resume', models.FileField(blank=True, upload_to='resumes/', verbose_name='Resume')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined On')),
            ],
            options={
                'verbose_name': 'Coliver',
                'verbose_name_plural': 'Colivers',
            },
        ),
    ]
