# Generated by Django 5.1.6 on 2025-03-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_coliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncoliver',
            name='check_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='Check-in Date'),
        ),
        migrations.AddField(
            model_name='noncoliver',
            name='move_out_date',
            field=models.DateField(blank=True, null=True, verbose_name='Move-out Date'),
        ),
    ]
