# Generated by Django 5.1.6 on 2025-03-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_noncoliver_check_in_date_noncoliver_move_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncoliver',
            name='nights',
            field=models.IntegerField(default=1, verbose_name='Nights'),
        ),
        migrations.AddField(
            model_name='noncoliver',
            name='room_type',
            field=models.CharField(default='standard', max_length=50, verbose_name='Room Type'),
        ),
        migrations.AddField(
            model_name='noncoliver',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Price'),
        ),
    ]
