# Generated by Django 5.1.6 on 2025-03-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_noncoliver_nights_noncoliver_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncoliver',
            name='guests',
            field=models.IntegerField(default=1, verbose_name='Number of Guests'),
        ),
        migrations.AddField(
            model_name='noncoliver',
            name='special_requests',
            field=models.TextField(blank=True, verbose_name='Special Requests'),
        ),
    ]
