# Generated by Django 5.1.6 on 2025-03-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_noncoliver_guests_noncoliver_special_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noncoliver',
            name='nights',
        ),
    ]
