# Generated by Django 5.1.6 on 2025-03-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='status',
            new_name='member_type',
        ),
        migrations.AddField(
            model_name='application',
            name='num_quests',
            field=models.CharField(choices=[('couple', 'couple'), ('individual', 'individual')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_join',
            field=models.DateField(blank=True, null=True, verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_leave',
            field=models.DateField(blank=True, null=True, verbose_name='Departure Date'),
        ),
    ]
