# Generated by Django 5.1.6 on 2025-03-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_status_application_member_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='num_quests',
            field=models.CharField(choices=[('couple', 'couple'), ('individual', 'individual')], default='individual', max_length=20, verbose_name='Number of Quests'),
        ),
    ]
