# Generated by Django 5.1.6 on 2025-03-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_num_quests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='num_quests',
        ),
        migrations.AddField(
            model_name='application',
            name='guests',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='2', max_length=2),
        ),
    ]
