# Generated by Django 5.1.6 on 2025-03-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_num_quests_application_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.AddField(
            model_name='application',
            name='question_1',
            field=models.TextField(blank=True, null=True, verbose_name='Question 1: Please tell us about yourself and your interest in Sacred Mountain'),
        ),
        migrations.AddField(
            model_name='application',
            name='question_2',
            field=models.TextField(blank=True, null=True, verbose_name='Question 2: What skills or contributions would you bring to our community?'),
        ),
        migrations.AddField(
            model_name='application',
            name='question_3',
            field=models.TextField(blank=True, null=True, verbose_name='Question 3: What are your expectations for your stay?'),
        ),
    ]
