# Generated by Django 5.1.6 on 2025-03-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_application_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='question_1',
            field=models.TextField(blank=True, null=True, verbose_name='Question 1: Please tell us about yourself and your interest in Seoul Nooks'),
        ),
    ]
