# Generated by Django 5.1.6 on 2025-03-09 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_status_alter_application_question_1'),
        ('chapters', '0005_chapter_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='chapters.chapter'),
        ),
    ]
