# Generated by Django 5.1.6 on 2025-03-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('approved for interview', 'approved for interview'), ('scheduled interview', 'scheduled interview'), ('interview passed', 'interview passed'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('waiting list', 'waiting list'), ('draft', 'Application in progress'), ('submitted', 'Submitted')], default='draft', max_length=40),
        ),
    ]
