# Generated by Django 5.1.6 on 2025-03-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_application_coupon_code_application_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
